name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: kubernetes
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: Deploy with terraform
        run: |
          make ci
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_ovh_service_name: ${{ secrets.OVH_SERVICE_NAME }} 
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}